name: project
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter_progress_hud: ^2.0.2
  animated_text_kit: ^4.2.2
  animations: ^2.0.8
  flutter:
    sdk: flutter
  flutter_sequence_animation: ^4.0.0
  rubber: ^1.1.0
  firebase_core: ^2.15.1
  cloud_firestore: ^4.9.1
  firebase_auth: ^4.9.0
  audioplayers: ^5.1.0
  assets_audio_player: ^3.1.1
  http: ^1.1.0
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Instpiration
      fonts:
        - asset: fonts/font1.ttf
  assets:
    - assets/images/
    - assets/sounds/
    
  
